apiVersion: v1
kind: LimitRange
metadata:
  name: gowebapp-system
  namespace: dev
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 250m
    defaultRequest: 
      memory: 256Mi
      cpu: 250m
    max: 
      cpu: 800m
    min: 
      cpu: 20m
    type: Container
